application:
    environment:
        php:
            version: 5.5.14
        timezone: 'Europe/Copenhagen'

    project_setup:
        before:
            - sudo service start mysql || true
            - composer install
            - php app/console doctrine:database:create
            - php app/console doctrine:schema:update --force

tools:
    external_code_coverage: false
    php_analyzer: true
    php_cpd: true
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    sensiolabs_security_checker: true

