koba_api:
    resource: "@KobaApiBundle/Resources/config/routing.yml"
    prefix:   /api

koba_admin:
    resource: "@KobaAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

itk_wayf:
    resource: "@ItkWayfBundle/Resources/config/routing.yml"
    prefix:   /auth

koba_main:
    resource: "@KobaMainBundle/Resources/config/routing.yml"
    prefix:   /

exchange:
    resource: "@ItkExchangeBundle/Resources/config/routing.yml"
    prefix:   /exchange
