koba_api:
    resource: "@KobaApiBundle/Resources/config/routing.yml"
    prefix:   /api

koba_admin:
    resource: "@KobaAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

koba_main:
    resource: "@KobaMainBundle/Resources/config/routing.yml"
    prefix:   /

exchange:
    resource: "@ItkExchangeBundle/Resources/config/routing.yml"
    prefix:   /exchange

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"