itk_api:
    resource: "@ItkApiBundle/Resources/config/routing.yml"
    prefix:   /api

itk_wayf:
    resource: "@ItkWayfBundle/Resources/config/routing.yml"
    prefix:   /auth


NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /doc

