security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Itk\ApiBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:         ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
            entity: { class: ItkApiBundle:User, property: id }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        logged_out:
            pattern: ^/api/logged_out
            security: false

        main:
            pattern: ^/
            logout:
                path: /api/logout
                target: /api/logged_out
            anonymous: true

    access_control:
        - { path: ^/auth/wayf/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/wayf/metadata$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/wayf/logout$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/logget_out$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
