parameters:

services:
  koba.users_service:
    class: Itk\ApiBundle\Services\UsersService
    arguments: [@service_container, @koba.helper_service]

  koba.roles_service:
    class: Itk\ApiBundle\Services\RolesService
    arguments: [@service_container, @koba.helper_service]

  koba.resources_service:
    class: Itk\ApiBundle\Services\ResourcesService
    arguments: [@service_container, @koba.helper_service, @koba.exchange_service]

  koba.bookings_service :
    class: Itk\ApiBundle\Services\BookingsService
    arguments: [@service_container, @koba.helper_service]

  koba.helper_service:
    class: Itk\ApiBundle\Services\HelperService
    arguments: [@service_container]

  koba.exchange_service :
    class: Itk\ApiBundle\Services\ExchangeService
    arguments: [@service_container, @koba.helper_service]
